---
abstract: 'A Perl module for protein contact interfaces evolutive analisys'
author:
  - 'Hector Valverde <hvalverde@uma.es>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Molevol-Complex
no_index:
  directory:
    - t
    - inc
requires:
  perl: 5.006
version: 1.01
